import { createOrder, nextAction, transitionOrder } from './order-engine.js';

const menu = [
  { id: 'biryani', name: 'Chicken Biryani', price: 320, category: 'Mains', stock: 12 }, { id: 'paneer', name: 'Paneer Tikka', price: 260, category: 'Mains', stock: 8 },
  { id: 'parotta', name: 'Malabar Parotta', price: 35, category: 'Breads', stock: 24 }, { id: 'coke', name: 'Coke', price: 50, category: 'Drinks', stock: 18 }, { id: 'lassi', name: 'Mango Lassi', price: 90, category: 'Drinks', stock: 3 },
];
const seed = [
  { id:'1',number:'L-1042',type:'Dine-in',table:'Table 6',status:'preparing',total:640,items:[{name:'Chicken Biryani',quantity:2}],createdAt:new Date(Date.now()-16*60000).toISOString(),history:[] },
  { id:'2',number:'L-1041',type:'Swiggy',status:'new',total:310,items:[{name:'Paneer Tikka',quantity:1}],createdAt:new Date(Date.now()-4*60000).toISOString(),history:[] },
  { id:'3',number:'L-1040',type:'Takeaway',status:'ready',total:370,items:[{name:'Chicken Biryani',quantity:1}],createdAt:new Date(Date.now()-11*60000).toISOString(),history:[] },
];
const labels = {new:'New',accepted:'Accepted',preparing:'Preparing',ready:'Ready',completed:'Completed',cancelled:'Cancelled'};
const money = new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0});
let view='Home', cart=[], orderType='Takeaway', notice='';
let orders = JSON.parse(localStorage.getItem('lefty-orders') || 'null') || seed;
const save = () => localStorage.setItem('lefty-orders', JSON.stringify(orders));
const active = () => orders.filter(o=>!['completed','cancelled'].includes(o.status));
const action = o => nextAction[o.status] ? `<button class="secondary" data-advance="${o.id}">${nextAction[o.status][0]}</button>` : '';
const status = s => `<span class="status ${s}">${labels[s]}</span>`;
const items = o => o.items.map(i=>`${i.quantity}× ${i.name}`).join(', ');
function orderRow(o) { return `<article class="order-row"><div><strong>${o.number}</strong><p>${o.type}${o.table?` · ${o.table}`:''} · ${items(o)}</p></div>${status(o.status)}${action(o)}</article>`; }
function shell(content) { const nav=['Home','Orders','POS','Floor','Menu','Availability','Kitchen','Attention','Settings']; return `<main class="shell"><aside><button class="brand" data-view="Home"><span>l</span> LEFTY</button><p class="outlet">Mango Tree · Main outlet</p><nav aria-label="Main navigation">${nav.map(n=>`<button class="${view===n?'active':''}" data-view="${n}">${n}${n==='Attention'?'<b>2</b>':''}</button>`).join('')}</nav><div class="profile"><strong>AM</strong><span>Aisha · Manager</span></div></aside><section class="workspace"><header><div><p class="eyebrow">FRIDAY, 18 SEPTEMBER</p><h1>${view==='Home'?'Good afternoon, Aisha.':view}</h1></div><button class="primary" data-view="POS">＋ New order</button></header>${notice?`<div class="notice" role="status">${notice}<button data-dismiss aria-label="Dismiss message">×</button></div>`:''}${content}</section></main>`; }
function home() { const a=active(), count=s=>a.filter(o=>o.status===s).length; return `<div class="summary">${[['New orders',count('new'),'Orders'],['Preparing',count('preparing'),'Kitchen'],['Ready to go',count('ready'),'Orders']].map(([name,n,target])=>`<button data-view="${target}"><span>${name}</span><strong>${n}</strong><small>Review now →</small></button>`).join('')}</div><div class="split"><section class="panel"><div class="panel-head"><div><h2>Needs your attention</h2><p>Take care of these next.</p></div><button class="text" data-view="Attention">View all</button></div><div class="attention"><span class="warning">!</span><div><strong>Mango Lassi is running low</strong><p>3 servings left. Make unavailable before it runs out.</p></div><button class="secondary" data-view="Availability">Check stock</button></div><div class="attention"><span class="warning">!</span><div><strong>One order is taking longer than usual</strong><p>L-1042 has been preparing for 16 minutes.</p></div><button class="secondary" data-view="Kitchen">Open kitchen</button></div></section><section class="panel orders-panel"><div class="panel-head"><div><h2>Active orders</h2><p>${a.length} orders in progress</p></div><button class="text" data-view="Orders">View orders</button></div>${a.map(orderRow).join('')}</section></div>`; }
function ordersView() { return `<section class="panel full"><div class="toolbar"><input id="search" aria-label="Search orders" placeholder="Search order number or channel"><span>${orders.length} orders</span></div><div class="table"><div class="thead"><span>Order</span><span>Source</span><span>Status</span><span>Total</span><span>Action</span></div><div id="order-list">${orderTable(orders)}</div></div></section>`; }
function orderTable(list) { return list.map(o=>`<div class="tr"><strong>${o.number}<small>${o.table||items(o)}</small></strong><span>${o.type}</span>${status(o.status)}<span>${money.format(o.total)}</span><span>${action(o)}</span></div>`).join(''); }
function kitchen() { return `<p class="intro">Clear, live work for the kitchen. Start with new tickets.</p><div class="kitchen">${['new','accepted','preparing','ready'].map(s=>`<section><h2>${labels[s]} <span>${active().filter(o=>o.status===s).length}</span></h2>${active().filter(o=>o.status===s).map(o=>`<article class="ticket"><div><span class="ticket-number">${o.number}</span><span>${Math.max(1,Math.round((Date.now()-new Date(o.createdAt))/60000))} min</span></div>${o.items.map(i=>`<p><b>${i.quantity}×</b> ${i.name}</p>`).join('')} ${nextAction[o.status]?`<button class="primary" data-advance="${o.id}">${nextAction[o.status][0]}</button>`:''}</article>`).join('')}</section>`).join('')}</div>`; }
function pos() { const total=cart.reduce((sum,x)=>sum+x.price*x.quantity,0); return `<div class="pos"><section><div class="order-type" role="group" aria-label="Order type">${['Dine-in','Takeaway','Delivery'].map(t=>`<button class="${orderType===t?'selected':''}" data-type="${t}">${t}</button>`).join('')}</div><h2>What would you like to add?</h2><div class="products">${menu.map(i=>`<button data-add="${i.id}"><span>${i.category}</span><strong>${i.name}</strong><small>${money.format(i.price)} · ${i.stock} left</small></button>`).join('')}</div></section><aside class="cart"><h2>New ${orderType} order</h2>${cart.length?cart.map(i=>`<div class="cart-item"><div><strong>${i.name}</strong><span>${money.format(i.price)}</span></div><div><button data-change="${i.id}" data-delta="-1" aria-label="Remove one ${i.name}">−</button><b>${i.quantity}</b><button data-change="${i.id}" data-delta="1" aria-label="Add one ${i.name}">＋</button></div></div>`).join(''):'<p class="empty">Choose items from the menu.<br>Your order will appear here.</p>'}<footer><div><span>Total</span><strong>${money.format(total)}</strong></div><button class="primary" data-create ${cart.length?'':'disabled'}>Take cash & send to kitchen</button></footer></aside></div>`; }
function floor() { return `<p class="intro">Choose a table to see the next action.</p><div class="floor">${[1,2,3,4,5,6,7,8].map(n=>`<button class="${n===6?'occupied':''}" data-view="${n===6?'Orders':'POS'}"><strong>Table ${n}</strong><span>${n===6?'Preparing · L-1042':'Available'}</span></button>`).join('')}</div>`; }
function placeholder() { return `<section class="panel empty-panel"><span>Coming next</span><h2>${view} is not available in this first operational slice.</h2><p>We have not added a non-functional screen. The unified POS, order lifecycle, kitchen queue, availability warning and table workflow above are working locally in this browser.</p></section>`; }
function render() { const body=view==='Home'?home():view==='Orders'?ordersView():view==='Kitchen'?kitchen():view==='POS'?pos():view==='Floor'?floor():placeholder(); document.querySelector('#root').innerHTML=shell(body); bind(); }
function bind() { document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render();}); document.querySelector('[data-dismiss]')?.addEventListener('click',()=>{notice='';render();}); document.querySelectorAll('[data-advance]').forEach(b=>b.onclick=()=>{const o=orders.find(x=>x.id===b.dataset.advance); const [,next]=nextAction[o.status]; orders=orders.map(x=>x.id===o.id?transitionOrder(x,next):x); save();notice=`${o.number} is now ${labels[next].toLowerCase()}.`;render();}); document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{orderType=b.dataset.type;render();}); document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const item=menu.find(x=>x.id===b.dataset.add), old=cart.find(x=>x.id===item.id);cart=old?cart.map(x=>x.id===item.id?{...x,quantity:x.quantity+1}:x):[...cart,{...item,quantity:1}];render();}); document.querySelectorAll('[data-change]').forEach(b=>b.onclick=()=>{const delta=Number(b.dataset.delta);cart=cart.flatMap(x=>x.id===b.dataset.change&&x.quantity+delta<=0?[]:x.id===b.dataset.change?[{...x,quantity:x.quantity+delta}]:[x]);render();}); document.querySelector('[data-create]')?.addEventListener('click',()=>{try{const o=createOrder({type:orderType,items:cart,paymentMethod:'Cash'});orders=[o,...orders];save();cart=[];notice=`${o.number} created and sent to kitchen.`;view='Orders';render();}catch(e){notice=e.message;render();}}); document.querySelector('#search')?.addEventListener('input',e=>document.querySelector('#order-list').innerHTML=orderTable(orders.filter(o=>`${o.number} ${o.type}`.toLowerCase().includes(e.target.value.toLowerCase())))); }
render();
